INSERT INTO source_catalog (
    source_name,
    source_type,
    base_url,
    reliability_score,
    expected_signal_type,
    collection_cost,
    rate_limit_policy,
    enabled
)
VALUES
    ('arXiv_robotics', 'rss', 'https://rss.arxiv.org/rss/cs.RO', 0.90, 'research', 'free', '{"stale_minutes": 10080, "channel": "arxiv", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('arXiv_AI', 'rss', 'https://rss.arxiv.org/rss/cs.AI', 0.85, 'research', 'free', '{"stale_minutes": 10080, "channel": "arxiv", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('arXiv_ML', 'rss', 'https://rss.arxiv.org/rss/cs.LG', 0.85, 'research', 'free', '{"stale_minutes": 10080, "channel": "arxiv", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('IEEE_Spectrum', 'rss', 'https://spectrum.ieee.org/feeds/feed.rss', 0.80, 'industry_news', 'free', '{"stale_minutes": 4320, "channel": "news", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('MIT_Tech_Review', 'rss', 'https://www.technologyreview.com/feed/', 0.80, 'industry_news', 'free', '{"stale_minutes": 2880, "channel": "news", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('TechCrunch_robotics', 'rss', 'https://techcrunch.com/tag/robotics/feed/', 0.65, 'startup_news', 'free', '{"stale_minutes": 4320, "channel": "news", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('Boston_Dynamics', 'rss', 'https://feeds.feedburner.com/BostonDynamics', 0.75, 'company_blog', 'free', '{"stale_minutes": 43200, "channel": "company_blog", "collection_mode": "rss_pull", "activation_policy": "always_on", "preferred_worker": "mini", "notes": "공개 RSS"}'::jsonb, TRUE),
    ('reddit_robotics_search', 'api', 'https://www.reddit.com/r/robotics/search.json?q=robotics&restrict_sr=1&sort=new', 0.55, 'community_signal', 'free', '{"channel": "reddit", "collection_mode": "community_api", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "Reddit API 자격증명 필요"}'::jsonb, FALSE),
    ('hackernews_robotics_search', 'api', 'https://hn.algolia.com/api/v1/search?query=robotics', 0.55, 'community_signal', 'free', '{"channel": "forum", "collection_mode": "community_api", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "공개 API, 현재 미배선"}'::jsonb, FALSE),
    ('youtube_robotics_search', 'api', 'https://www.youtube.com/results?search_query=robotics', 0.50, 'video_signal', 'free', '{"channel": "youtube", "collection_mode": "discovery", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "YouTube Data API 또는 browser worker 필요"}'::jsonb, FALSE),
    ('substack_publication_discovery', 'newsletter', 'https://substack.com', 0.60, 'newsletter_post', 'free', '{"channel": "substack", "collection_mode": "rss_search", "activation_policy": "always_on", "preferred_worker": "mbp", "notes": "SUBSTACK_SOURCE_FEEDS 또는 SUBSTACK_PUBLICATION_URL 기반 /feed 수집"}'::jsonb, TRUE),
    ('maily_publication_discovery', 'newsletter', 'https://maily.so', 0.45, 'newsletter_post', 'free', '{"channel": "maily", "collection_mode": "browser_search", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "브라우저 탐색 기반, 소유권 없는 계정 직접 크롤링 금지"}'::jsonb, FALSE),
    ('brunch_story_discovery', 'browser', 'https://brunch.co.kr', 0.45, 'creator_post', 'free', '{"channel": "brunch", "collection_mode": "browser_search", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "브라우저 탐색 기반"}'::jsonb, FALSE),
    ('naver_blog_search', 'browser', 'https://search.naver.com/search.naver?where=view&query=robotics', 0.50, 'creator_post', 'free', '{"channel": "naver_blog", "collection_mode": "browser_search", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "공개 검색 결과 기반"}'::jsonb, FALSE),
    ('naver_cafe_search', 'browser', 'https://search.naver.com/search.naver?where=article&query=robotics', 0.45, 'community_signal', 'free', '{"channel": "naver_cafe", "collection_mode": "browser_search", "activation_policy": "restricted", "preferred_worker": "mbp", "requires_login": true, "notes": "카페별 접근권한/로그인 이슈"}'::jsonb, FALSE),
    ('x_robotics_search', 'social', 'https://x.com/search?q=robotics', 0.40, 'social_signal', 'free', '{"channel": "x", "collection_mode": "browser_search", "activation_policy": "restricted", "preferred_worker": "mbp", "requires_login": true, "notes": "공식 API 또는 승인된 browser worker 필요"}'::jsonb, FALSE),
    ('threads_robotics_search', 'social', 'https://www.threads.net/search?q=robotics', 0.35, 'social_signal', 'free', '{"channel": "threads", "collection_mode": "browser_search", "activation_policy": "restricted", "preferred_worker": "mbp", "requires_login": true, "notes": "로그인/정책 이슈"}'::jsonb, FALSE),
    ('instagram_robotics_search', 'social', 'https://www.instagram.com/explore/search/keyword/?q=robotics', 0.30, 'social_signal', 'free', '{"channel": "instagram", "collection_mode": "browser_search", "activation_policy": "restricted", "preferred_worker": "mbp", "requires_login": true, "notes": "로그인/anti-bot 이슈"}'::jsonb, FALSE),
    ('discord_public_servers', 'community', 'https://discord.com', 0.35, 'community_signal', 'free', '{"channel": "discord", "collection_mode": "manual", "activation_policy": "restricted", "preferred_worker": "mbp", "requires_login": true, "notes": "서버별 권한 필요, webhook/export 없으면 자동 수집 금지"}'::jsonb, FALSE),
    ('forum_thread_discovery', 'rss_search', 'https://news.google.com/rss/search?q=robotics+forum', 0.40, 'community_signal', 'free', '{"channel": "thread", "collection_mode": "rss_search", "activation_policy": "discovery", "preferred_worker": "mbp", "notes": "포럼/스레드 발견용 공개 RSS"}'::jsonb, FALSE)
ON CONFLICT (source_name) DO UPDATE SET
    source_type = EXCLUDED.source_type,
    base_url = EXCLUDED.base_url,
    reliability_score = EXCLUDED.reliability_score,
    expected_signal_type = EXCLUDED.expected_signal_type,
    collection_cost = EXCLUDED.collection_cost,
    rate_limit_policy = EXCLUDED.rate_limit_policy,
    enabled = EXCLUDED.enabled,
    updated_at = NOW();
